import puppeteer from "puppeteer-core";
const [,, path, out, theme] = process.argv;
const b = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: true });
const p = await b.newPage();
await p.setViewport({ width: 1400, height: 900 });
if (theme) await p.evaluateOnNewDocument((t) => localStorage.setItem("theme", t), theme);
await p.goto(`http://localhost:3100${path}`, { waitUntil: "networkidle2" });
await new Promise(r => setTimeout(r, 7000));
await p.screenshot({ path: out });
await b.close();
console.log("saved", out);
