import puppeteer from "puppeteer-core";
const b = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: true });
const p = await b.newPage(); await p.setViewport({ width: 1400, height: 900 });
const errs=[]; p.on("pageerror",e=>errs.push(e.message));
await p.goto("http://localhost:3192/mirror",{waitUntil:"domcontentloaded",timeout:60000});
await new Promise(r=>setTimeout(r,3000));
await p.type(".dock input","なぜ私は"); await p.keyboard.press("Enter"); await new Promise(r=>setTimeout(r,1500));
await p.type(".dock input","どうすれば幸せ"); await p.keyboard.press("Enter"); await new Promise(r=>setTimeout(r,2500));
await p.screenshot({path:"/tmp/declutter.png"});
console.log("ERRORS:", errs.length?errs.join("; "):"(none)");
await b.close();
